export const DIAMANT_LISTE_REQUEST = 'DIAMANT_LISTE_REQUEST';
export const DIAMANT_LISTE_SUCCESS = 'DIAMANT_LISTE_SUCCESS';
export const DIAMANT_LISTE_FAIL = 'DIAMANT_LISTE_FAIL';
export const DIAMANT_DETAILS_REQUEST = 'DIAMANT_DETAILS_REQUEST';
export const DIAMANT_DETAILS_SUCCESS = 'DIAMANT_DETAILS_SUCCESS';
export const DIAMANT_DETAILS_FAIL = 'DIAMANT_DETAILS_FAIL';

export const DIAMANT_CREATE_REQUEST = 'DIAMANT_CREATE_REQUEST';
export const DIAMANT_CREATE_SUCCESS = 'DIAMANT_CREATE_SUCCESS';
export const DIAMANT_CREATE_FAIL = 'DIAMANT_CREATE_FAIL';
export const DIAMANT_CREATE_RESET = 'DIAMANT_CREATE_RESET';

export const DIAMANT_UPDATE_REQUEST = 'DIAMANT_UPDATE_REQUEST';
export const DIAMANT_UPDATE_SUCCESS = 'DIAMANT_UPDATE_SUCCESS';
export const DIAMANT_UPDATE_FAIL = 'DIAMANT_UPDATE_FAIL';
export const DIAMANT_UPDATE_RESET = 'DIAMANT_UPDATE_RESET';

export const DIAMANT_DELETE_REQUEST = 'DIAMANT_DELETE_REQUEST';
export const DIAMANT_DELETE_SUCCESS = 'DIAMANT_DELETE_SUCCESS';
export const DIAMANT_DELETE_FAIL = 'DIAMANT_DELETE_FAIL';
export const DIAMANT_DELETE_RESET = 'DIAMANT_DELETE_RESET'



