export const RECOMMANDATION_ADD_ITEM='RECOMMANDATION__ADD_ITEM';
export const RECOMMANDATION_REMOVE_ITEM='RECOMMANDATION__REMOVE_ITEM';
export const RECOMMANDATION__ADD_ITEM_FAIL='RECOMMANDATION__ADD_ITEM_FAIL';
export const RECOMMANDATION__SAVE_SHIPPING_ADDRESS = 'RECOMMANDATION__SAVE_SHIPPING_ADDRESS';
export const RECOMMANDATION__SAVE_PAYMENT_METHOD = 'RECOMMANDATION__SAVE_PAYMENT_METHOD';
export const RECOMMANDATION__EMPTY='RECOMMANDATION__EMPTY';
